-- MySQL Script generated by MySQL Workbench
-- Wed 06 Sep 2017 21:50:59 UTC
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_type` (
  `user_type_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `slug` VARCHAR(128) UNIQUE NOT NULL,
  `display_name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date`  NULL,
  PRIMARY KEY (`user_type_id`));


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `user_type_id` VARCHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `confirmed_at` DATETIME NULL,
  `current_login_at` DATETIME NULL,
  `current_login_ip` VARCHAR(45) NULL,
  `last_login_at` DATETIME NULL,
  `last_login_ip` VARCHAR(45) NULL,
  `login_count` INT(11) NOT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `role_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `parent_role_id` VARCHAR(36) NULL,
  `role_type_id` VARCHAR(36) NOT NULL,
  `display_name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`role_id`));


-- -----------------------------------------------------
-- Table `role_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_type` (
  `role_type_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `slug` VARCHAR(128) UNIQUE NOT NULL,
  `display_name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`role_type_id`));


-- -----------------------------------------------------
-- Table `organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization` (
  `organization_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `parent_organization_id` VARCHAR(36) NULL,
  `organization_type_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`organization_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organization_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_type` (
  `organization_type_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `slug` VARCHAR(128) UNIQUE NOT NULL,
  `display_name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`organization_type_id`));


-- -----------------------------------------------------
-- Table `metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metadata` (
  `tablename_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`tablename_id`));


-- -----------------------------------------------------
-- Table `organization_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_user_role` (
  `organization_user_role_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `organization_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`organization_user_role_id`));


-- -----------------------------------------------------
-- Table `organization_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_address` (
  `organization_address_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `organization_id` VARCHAR(36) NOT NULL,
  `address_line_1` VARCHAR(255) NOT NULL DEFAULT 1,
  `address_line_2` VARCHAR(255) NULL,
  `city` VARCHAR(255) NOT NULL,
  `state_province` VARCHAR(128) NOT NULL,
  `country_id` VARCHAR(45) NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`organization_address_id`));


-- -----------------------------------------------------
-- Table `address_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address_type` (
  `address_type_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `slug` VARCHAR(128) UNIQUE NOT NULL,
  `display_name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`address_type_id`));


-- -----------------------------------------------------
-- Table `contact_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact_type` (
  `contact_type_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `slug` VARCHAR(128) UNIQUE NOT NULL,
  `display_name` VARCHAR(255) UNIQUE NOT NULL,
  `description` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`contact_type_id`));


-- -----------------------------------------------------
-- Table `organization_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_contact` (
  `organization_contact_id` VARCHAR(36) UNIQUE NOT NULL DEFAULT uuid(),
  `organization_id` VARCHAR(36) NOT NULL,
  `contact_type_id` VARCHAR(36) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `display` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `created_by` VARCHAR(36) NOT NULL,
  `modified_date` DATETIME NULL,
  `modified_by` VARCHAR(36) NULL,
  `deactivated_date` DATETIME NULL,
  `deactivated_by` VARCHAR(36) NULL,
  `valid_from_date` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
  `valid_to_date` DATETIME NULL,
  PRIMARY KEY (`organization_contact_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
