-- MySQL Script generated by MySQL Workbench
-- Wed 06 Sep 2017 10:14:55 PM MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_proto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_type` (
  `user_type_id`  INT NOT NULL AUTO_INCREMENT,
  `user_type_uuid` VARCHAR(36) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_type_id`),
  UNIQUE INDEX `user_type_id` (`user_type_id` ASC),
  UNIQUE INDEX `slug` (`slug` ASC),
  UNIQUE INDEX `display_name` (`display_name` ASC),
  INDEX `fk_user_type_user1_idx` (`created_by` ASC),
  INDEX `fk_user_type_user2_idx` (`modified_by` ASC),
  INDEX `fk_user_type_user3_idx` (`deactivated_by` ASC),
  CONSTRAINT `fk_user_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user3`
    FOREIGN KEY (`deactivated_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_uuid` VARCHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `confirmed_at` DATETIME NULL DEFAULT NULL,
  `current_login_at` DATETIME NULL DEFAULT NULL,
  `current_login_ip` VARCHAR(45) NULL DEFAULT NULL,
  `last_login_at` DATETIME NULL DEFAULT NULL,
  `last_login_ip` VARCHAR(45) NULL DEFAULT NULL,
  `login_count` INT(11) NOT NULL DEFAULT '0',
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC),
  INDEX `fk_user_user_type1_idx` (`user_type_id` ASC),
  INDEX `fk_user_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `address_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address_type` (
  `address_type_id` INT NOT NULL AUTO_INCREMENT,
  `address_type_uuid` VARCHAR(36) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`address_type_id`),
  UNIQUE INDEX `address_type_id` (`address_type_id` ASC),
  UNIQUE INDEX `slug` (`slug` ASC),
  UNIQUE INDEX `display_name` (`display_name` ASC),
  INDEX `fk_address_type_user1_idx` (`created_by` ASC),
  INDEX `fk_address_type_user2_idx` (`modified_by` ASC),
  INDEX `fk_address_type_user3_idx` (`deactivated_by` ASC),
  CONSTRAINT `fk_address_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_type_user2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_type_user3`
    FOREIGN KEY (`deactivated_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `contact_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact_type` (
  `contact_type_id` INT NOT NULL AUTO_INCREMENT,
  `contact_type_uuid` VARCHAR(36) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`contact_type_id`),
  UNIQUE INDEX `contact_type_id` (`contact_type_id` ASC),
  UNIQUE INDEX `slug` (`slug` ASC),
  UNIQUE INDEX `display_name` (`display_name` ASC),
  INDEX `fk_contact_type_user1_idx` (`created_by` ASC),
  INDEX `fk_contact_type_user2_idx` (`modified_by` ASC),
  INDEX `fk_contact_type_user3_idx` (`deactivated_by` ASC),
  CONSTRAINT `fk_contact_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_type_user2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_type_user3`
    FOREIGN KEY (`deactivated_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metadata` (
  `tablename_id` INT NOT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`tablename_id`),
  UNIQUE INDEX `tablename_id` (`tablename_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `organization_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_type` (
  `organization_type_id` INT NOT NULL AUTO_INCREMENT,
  `organization_type_uuid` VARCHAR(36) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`organization_type_id`),
  UNIQUE INDEX `organization_type_id` (`organization_type_id` ASC),
  UNIQUE INDEX `slug` (`slug` ASC),
  UNIQUE INDEX `display_name` (`display_name` ASC),
  INDEX `fk_organization_type_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_organization_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization` (
  `organization_id` INT NOT NULL AUTO_INCREMENT,
  `organization_uuid` VARCHAR(36) NOT NULL,
  `parent_organization_id` VARCHAR(36) NULL DEFAULT NULL,
  `organization_type_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`organization_id`),
  UNIQUE INDEX `organization_id` (`organization_id` ASC),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `fk_organization_organization_type1_idx` (`organization_type_id` ASC),
  INDEX `fk_organization_organization1_idx` (`parent_organization_id` ASC),
  INDEX `fk_organization_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_organization_organization_type1`
    FOREIGN KEY (`organization_type_id`)
    REFERENCES `organization_type` (`organization_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_organization1`
    FOREIGN KEY (`parent_organization_id`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `organization_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_address` (
  `organization_address_id` INT NOT NULL AUTO_INCREMENT,
  `organization_address_uuid` VARCHAR(36) NOT NULL,
  `organization_id` INT NOT NULL,
  `address_type_id` INT NOT NULL,
  `address_line_1` VARCHAR(255) NOT NULL DEFAULT '1',
  `address_line_2` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state_province` VARCHAR(128) NOT NULL,
  `country_id` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`organization_address_id`),
  UNIQUE INDEX `organization_address_id` (`organization_address_id` ASC),
  INDEX `fk_organization_address_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_organization_address_address_type1_idx` (`address_type_id` ASC),
  INDEX `fk_organization_address_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_organization_address_organization_id`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_address_address_type1`
    FOREIGN KEY (`address_type_id`)
    REFERENCES `address_type` (`address_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_address_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `organization_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_contact` (
  `organization_contact_id` INT NOT NULL AUTO_INCREMENT,
`organization_contact_uuid` VARCHAR(36) NOT NULL,
  `organization_id` INT NOT NULL,
  `contact_type_id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`organization_contact_id`),
  UNIQUE INDEX `organization_contact_id` (`organization_contact_id` ASC),
  INDEX `fk_organization_contact_organization1_idx` (`organization_id` ASC),
  INDEX `fk_organization_contact_contact_type1_idx` (`contact_type_id` ASC),
  INDEX `fk_organization_contact_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_organization_contact_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_contact_contact_type1`
    FOREIGN KEY (`contact_type_id`)
    REFERENCES `contact_type` (`contact_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_contact_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `role_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_type` (
  `role_type_id` INT NOT NULL AUTO_INCREMENT,
`role_type_uuid` VARCHAR(36) NOT NULL,
  `organization_uuid` INT NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`role_type_id`),
  UNIQUE INDEX `role_type_id` (`role_type_id` ASC),
  UNIQUE INDEX `slug` (`slug` ASC),
  UNIQUE INDEX `display_name` (`display_name` ASC),
  INDEX `fk_role_type_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_role_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
`role_uuid` VARCHAR(36) NOT NULL,
  `parent_role_id` VARCHAR(36) NULL DEFAULT NULL,
  `role_type_id` INT NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id` (`role_id` ASC),
  UNIQUE INDEX `display_name` (`display_name` ASC),
  INDEX `fk_role_role1_idx` (`parent_role_id` ASC),
  INDEX `fk_role_role_type1_idx` (`role_type_id` ASC),
  INDEX `fk_role_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_role_role1`
    FOREIGN KEY (`parent_role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_role_type1`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `role_type` (`role_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `organization_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organization_user_role` (
  `organization_user_role_id` INT NOT NULL AUTO_INCREMENT,
`organization_user_role_uuid`VARCHAR(36) NOT NULL,
  `organization_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `active` TINYINT(4) NOT NULL DEFAULT '1',
  `display` TINYINT(4) NOT NULL DEFAULT '1',
  `created_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `modified_by` VARCHAR(36) NULL DEFAULT NULL,
  `deactivated_date` DATETIME NULL DEFAULT NULL,
  `deactivated_by` VARCHAR(36) NULL DEFAULT NULL,
  `valid_from_date` DATETIME NOT NULL,
  `valid_to_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`organization_user_role_id`),
  UNIQUE INDEX `organization_user_role_id` (`organization_user_role_id` ASC),
  INDEX `fk_organization_user_role_organization1_idx` (`organization_id` ASC),
  INDEX `fk_organization_user_role_user1_idx` (`user_id` ASC),
  INDEX `fk_organization_user_role_role1_idx` (`role_id` ASC),
  INDEX `fk_organization_user_role_user2_idx` (`created_by` ASC),
  CONSTRAINT `fk_organization_user_role_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_user_role_user2`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
